global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus1:9090']
  - job_name: 'classificationbox'
    static_configs:
    - targets: ['classificationbox1:8080'] # replace this with actual IP address
