version: '3'
services:
  classificationbox1:
    image: machinebox/classificationbox
    environment:
      - MB_KEY=${MB_KEY}
      - MB_WORKERS=1
    ports:
      - "8080:8080"
  # optionally you can monitor the box with prometheus
  # prometheus1:
  #   image: prom/prometheus
  #   volumes:
  #     - ./config:/prometheus
  #   command:
  #     - '--config.file=/prometheus/prometheus.yml'
  #   ports:
  #     - "9090:9090"
